//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyranoScriptMemoryUnlocker.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TyranoScriptMemoryUnlocker.Res.LocalizedString", typeof(LocalizedString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not affiliated with TyranoScript..
        /// </summary>
        public static string AppDisclaimer {
            get {
                return ResourceManager.GetString("AppDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under AGPLv3-and-later.
        /// </summary>
        public static string AppLic {
            get {
                return ResourceManager.GetString("AppLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save file has been updated successfully..
        /// </summary>
        public static string AppSuccess_Line1 {
            get {
                return ResourceManager.GetString("AppSuccess_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the unlocked contents in CG or Memory mode!.
        /// </summary>
        public static string AppSuccess_Line2 {
            get {
                return ResourceManager.GetString("AppSuccess_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked CGs: {0}.
        /// </summary>
        public static string AppSuccess_Line3 {
            get {
                return ResourceManager.GetString("AppSuccess_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked Replays: {0}.
        /// </summary>
        public static string AppSuccess_Line4 {
            get {
                return ResourceManager.GetString("AppSuccess_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string ArgErrorUnknown {
            get {
                return ResourceManager.GetString("ArgErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid for arg: {0}.
        /// </summary>
        public static string ArgInvalid {
            get {
                return ResourceManager.GetString("ArgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required option: {0}.
        /// </summary>
        public static string ArgMissing {
            get {
                return ResourceManager.GetString("ArgMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option:.
        /// </summary>
        public static string ArgUnknown {
            get {
                return ResourceManager.GetString("ArgUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a tool to unlock CGs and replays in TyranoScript-based games/visual novels by modifying the save file..
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry run mode enabled. No changes will be made to the save file..
        /// </summary>
        public static string DryModeNotice {
            get {
                return ResourceManager.GetString("DryModeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .asar file path &apos;{0}&apos; does not exist..
        /// </summary>
        public static string ErrorAsarNotFound {
            get {
                return ResourceManager.GetString("ErrorAsarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the asar or save file..
        /// </summary>
        public static string ErrorAsarSav {
            get {
                return ResourceManager.GetString("ErrorAsarSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try &apos;{0} --help&apos; for more information..
        /// </summary>
        public static string ErrorHelpCmd {
            get {
                return ResourceManager.GetString("ErrorHelpCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .sav file path &apos;{0}&apos; does not exist..
        /// </summary>
        public static string ErrorSavNotFound {
            get {
                return ResourceManager.GetString("ErrorSavNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid .sav file..
        /// </summary>
        public static string ExcInvalidSav {
            get {
                return ResourceManager.GetString("ExcInvalidSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid [&apos;{0}&apos;] in .sav file..
        /// </summary>
        public static string ExcInvalidView {
            get {
                return ResourceManager.GetString("ExcInvalidView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} script files in asar..
        /// </summary>
        public static string FoundAsarScripts {
            get {
                return ResourceManager.GetString("FoundAsarScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} Unlockable CGs..
        /// </summary>
        public static string FoundCGs {
            get {
                return ResourceManager.GetString("FoundCGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} Unlockable Replays..
        /// </summary>
        public static string FoundReplays {
            get {
                return ResourceManager.GetString("FoundReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario scripts:.
        /// </summary>
        public static string FoundScripts {
            get {
                return ResourceManager.GetString("FoundScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the app.asar file containing the game scripts. (typically in &apos;resources/&apos;).
        /// </summary>
        public static string HelpTextAsar {
            get {
                return ResourceManager.GetString("HelpTextAsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Description:{1}    {0}{1}{1}Usage:{1}    tsmu [options] -a &lt;path&gt; -s &lt;path&gt;{1}{1}    &lt;path&gt; {2}{1}{1}Options:.
        /// </summary>
        public static string HelpTextDesc {
            get {
                return ResourceManager.GetString("HelpTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry run mode. Only show what would be done, without modifying the save file..
        /// </summary>
        public static string HelpTextDryRun {
            get {
                return ResourceManager.GetString("HelpTextDryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays this help screen..
        /// </summary>
        public static string HelpTextHelp {
            get {
                return ResourceManager.GetString("HelpTextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the File&apos;s path..
        /// </summary>
        public static string HelpTextOptPath {
            get {
                return ResourceManager.GetString("HelpTextOptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Required Option&gt;.
        /// </summary>
        public static string HelpTextRequired {
            get {
                return ResourceManager.GetString("HelpTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the sav(e) file to modify. (typically in game top folder).
        /// </summary>
        public static string HelpTextSav {
            get {
                return ResourceManager.GetString("HelpTextSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase verbosity. Can be stacked -vv, up to 2 levels..
        /// </summary>
        public static string HelpTextVerbose {
            get {
                return ResourceManager.GetString("HelpTextVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted? Is the game running fine? (!!)Delete and re-run the game(!!) ONLY IF YOU ARE SURE (!!).
        /// </summary>
        public static string JsonExc {
            get {
                return ResourceManager.GetString("JsonExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =========================================================.
        /// </summary>
        public static string LogLine {
            get {
                return ResourceManager.GetString("LogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ======================== DONE !! ========================.
        /// </summary>
        public static string LogLineDone {
            get {
                return ResourceManager.GetString("LogLineDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ====================== THANK YOU ! ======================.
        /// </summary>
        public static string LogLineTY {
            get {
                return ResourceManager.GetString("LogLineTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening asar file: {0}.
        /// </summary>
        public static string OpenAsar {
            get {
                return ResourceManager.GetString("OpenAsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening sav file: {0}.
        /// </summary>
        public static string OpenSav {
            get {
                return ResourceManager.GetString("OpenSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up save file &apos;{0}&apos;-&gt;&apos;{1}&apos;.
        /// </summary>
        public static string SavBackup {
            get {
                return ResourceManager.GetString("SavBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup cancelled because of dry run..
        /// </summary>
        public static string SavBackupCancel {
            get {
                return ResourceManager.GetString("SavBackupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would backup save file &apos;{0}&apos;-&gt;&apos;{1}&apos;.
        /// </summary>
        public static string SavBackupDry {
            get {
                return ResourceManager.GetString("SavBackupDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes to the save file: {0}.
        /// </summary>
        public static string SavingSav {
            get {
                return ResourceManager.GetString("SavingSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would write to {0}.
        /// </summary>
        public static string SavingSavDry {
            get {
                return ResourceManager.GetString("SavingSavDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing list from JSON..
        /// </summary>
        public static string SavJsonParse {
            get {
                return ResourceManager.GetString("SavJsonParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializing changes to JSON..
        /// </summary>
        public static string SavJsonSerialize {
            get {
                return ResourceManager.GetString("SavJsonSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlockable CGs:.
        /// </summary>
        public static string UnlockableCGs {
            get {
                return ResourceManager.GetString("UnlockableCGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlockable Replays:.
        /// </summary>
        public static string UnlockableReplays {
            get {
                return ResourceManager.GetString("UnlockableReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Unlocked {0} CGs..
        /// </summary>
        public static string UnlockedCGs {
            get {
                return ResourceManager.GetString("UnlockedCGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Unlocked CGs in save:.
        /// </summary>
        public static string UnlockedCGsAlr {
            get {
                return ResourceManager.GetString("UnlockedCGsAlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Unlocked {0} Replays..
        /// </summary>
        public static string UnlockedReplays {
            get {
                return ResourceManager.GetString("UnlockedReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Unlocked Replays in save:.
        /// </summary>
        public static string UnlockedReplaysAlr {
            get {
                return ResourceManager.GetString("UnlockedReplaysAlr", resourceCulture);
            }
        }
    }
}
